{
  "openapi": "3.0.0",
  "info": {
    "title": "Trello Clone API",
    "version": "v1",
    "description": "header === body",
    "contact": {
      "email": "kachanovski03@gmail.com",
      "name": "Alexander Kachanovski"
    }
  },
  "externalDocs": {
    "url": "/"
  },
  "servers": [
    {
      "url": "https://trello-app-clone.herokuapp.com/"
    }
  ],
  "tags": [
    {"name": "auth"},
    {"name": "boards"},
    {"name": "column"},
    {"name": "cards"}
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "summary": "login",
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "name": "data",
            "in": "header",
            "required": true,
            "description": "Data for Login",
            "schema": {
              "type": "object",
              "example": {
                "email": "string",
                "password": "string",
                "rememberMe": false
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "data": {
                      "email": "string",
                      "userName": "string || ===email"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "summary": "register",
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "name": "data",
            "in": "header",
            "required": true,
            "description": "data for register",
            "schema": {
              "example": {
                "email": "string",
                "password": "string"
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "string",
                  "example": {
                    "resultCode": 0,
                    "message": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/me": {
      "get": {
        "summary": "authMe",
        "tags": [
          "auth"
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "data": {
                      "id": "string",
                      "email": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/logout": {
      "delete": {
        "summary": "logOut",
        "tags": [
          "auth"
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "message": "string"
                  }
                }
              }
            }
          }
        }
      }
    },


    "/boards": {
      "get": {
        "summary": "allBoards",
        "tags": [
          "boards"
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "data": {
                      "boards": "Array Boards"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "addBoard",
        "tags": [
          "boards"
        ],
        "parameters": [
          {
            "name": "boardData",
            "in": "path",
            "required": true,
            "description": "board data",
            "schema": {
              "type": "object",
              "example": {
                "title": "string",
                "author_id": "string"
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "message": "Board added"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/boards/{id}": {
      "get": {
        "summary": "findBoard",
        "tags": [
          "boards"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "board id",
            "schema": {
              "type": "string",
              "example": {
                "id": "string"
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "data": {
                      "board": {
                        "id": "string",
                        "title": "string",
                        "author_id": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "updateBoard",
        "tags": [
          "boards"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "board id",
            "schema": {
              "type": "string",
              "example": {
                "id": "string"
              }
            }
          },
          {
            "name": "board",
            "in": "header",
            "required": true,
            "description": "board data",
            "schema": {
              "type": "object",
              "example": {
                "title": "string"
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "data": {
                      "board": {
                        "id": "string",
                        "title": "string",
                        "author_id": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "deleteBoard",
        "tags": [
          "boards"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "board id",
            "schema": {
              "type": "string",
              "example": {
                "id": "string"
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "message": "board deleted"
                  }
                }
              }
            }
          }
        }
      }
    },


    "/column": {
      "get": {
        "summary": "getColumns",
        "tags": [
          "column"
        ],
        "parameters": [
          {
            "name": "Board ID",
            "in": "query",
            "required": true,
            "description": "board_id",
            "schema": {
              "type": "string",
              "example": "board_id"
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "data": {
                      "columns": "columns<Array<ColumnType>>",
                      "count": "count columns"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "addColumn",
        "tags": [
          "column"
        ],
        "parameters": [
          {
            "name": "Board ID",
            "in": "query",
            "required": true,
            "description": "board_id",
            "schema": {
              "type": "string",
              "example": "board_id"
            }
          },
          {
            "name": "Column data",
            "in": "header",
            "required": true,
            "description": "Column data",
            "schema": {
              "type": "object",
              "example": {
                "title": "string"
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "message": "Column added"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/column/{id)": {
      "delete": {
        "summary": "delete column",
        "tags": [
          "column"
        ],
        "parameters": [
          {
            "name": "Column ID",
            "in": "path",
            "required": true,
            "description": "Column",
            "schema": {
              "type": "string",
              "example": "ColumnId"
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "message": "column deleted"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "updateColumn",
        "tags": [
          "column"
        ],
        "parameters": [
          {
            "name": "column ID",
            "in": "path",
            "required": true,
            "description": "column id",
            "schema": {
              "type": "string",
              "example": "column id"
            }
          },
          {
            "name": "Column data",
            "in": "header",
            "required": true,
            "description": "Column data",
            "schema": {
              "type": "object",
              "example": {
                "title": "string"
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "message": "Column updated"
                  }
                }
              }
            }
          }
        }
      }

    },


    "/cards": {
      "get": {
        "summary": "getCards",
        "tags": [
          "cards"
        ],
        "parameters": [
          {
            "name": "column ID",
            "in": "query",
            "required": true,
            "description": "column_id",
            "schema": {
              "type": "string",
              "example": "column_id"
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "data": {
                      "columns": "cards<Array<CardsType>>",
                      "count": "count cards"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "addCards",
        "tags": [
          "cards"
        ],
        "parameters": [
          {
            "name": "column ID",
            "in": "query",
            "required": true,
            "description": "column_id",
            "schema": {
              "type": "string",
              "example": "column_id"
            }
          },
          {
            "name": "Card data",
            "in": "header",
            "required": true,
            "description": "card data",
            "schema": {
              "type": "object",
              "example": {
                "title": "string"
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "message": "Card added"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/cards/{id)": {
      "delete": {
        "summary": "delete card",
        "tags": [
          "cards"
        ],
        "parameters": [
          {
            "name": "Card ID",
            "in": "path",
            "required": true,
            "description": "Card id",
            "schema": {
              "type": "string",
              "example": "CardId"
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "message": "card deleted"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "updateCard",
        "tags": [
          "cards"
        ],
        "parameters": [
          {
            "name": "card ID",
            "in": "path",
            "required": true,
            "description": "column id",
            "schema": {
              "type": "string",
              "example": "card id"
            }
          },
          {
            "name": "Card data",
            "in": "header",
            "required": true,
            "description": "Card data",
            "schema": {
              "type": "object",
              "example": {
                "title": "string"
              }
            }
          }
        ],
        "description": "Parameters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "example": {
                    "resultCode": 0,
                    "message": "Card updated"
                  }
                }
              }
            }
          }
        }
      }

    }


  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "userName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "rememberMe": {
            "type": "boolean"
          },
          "teams": {
            "type": "array"
          },
          "boards": {
            "type": "array"
          },
          "verified": {
            "type": "boolean"
          },
          "avatar": {
            "type": "string"
          },
          "token": {
            "type": "string"
          },
          "tokenDeathTime": {
            "type": "number"
          },
          "resetPasswordToken": {
            "type": "string"
          },
          "resetPasswordTokenDeathTime": {
            "type": "number"
          }
        }
      },
      "Board": {
        "type": "object",
        "properties": {
          "author_id": {
            "type": "string"
          },
          "_id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "created": {
            "type": "string"
          }
        }
      },
      "Column": {
        "type": "object",
        "properties": {
          "board_id": {
            "type": "string"
          },
          "_id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "created": {
            "type": "string"
          }
        }
      },
      "Card": {
        "type": "object",
        "properties": {
          "board_id": {
            "type": "string"
          },
          "_id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "created": {
            "type": "string"
          }
        }
      }
    }
  }
}